### PR TITLE
Fix SMDH Header being Cleared

### PR DESCRIPTION
**Pull request by usagirei**
And erasing the Magic in the process

### CODE REVIEW

**Comment by Steveice10** [comment]
You're right, that clear shouldn't be necessary. You can go ahead and remove the remaining memsets you commented above, and I'll pull it.

**Comment by usagirei** [comment]
Removed them, should be good now.

One other not really an issue, is that SMDH is being passed by copy where it could be being passed by reference to cmd_create_smdh (its a rather big struct data wise), but it's not the scope for this PR

**Comment by usagirei** [comment]
Now all we need is an update for buildtools binaries (All this to get the Title Name showing in FBI)

Thanks @Steveice10 :+1:

**Comment by Steveice10** [comment]
Binaries have been updated for Windows and Linux.

**Pull request merged**
